# Site settings
title: Iran University of Science and Technology
course_name: Deep Learning
course_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ornare aliquam mattis. Donec hendrerit sollicitudin urna. Aliquam venenatis rutrum velit, at lobortis dui cursus a. Nam varius metus in turpis maximus, ut rhoncus tellus dictum. In aliquam tortor nec mi dapibus, sit amet vehicula dolor auctor."
course_semester: "Spring 1398"
description: |
    Instructor: Mohammad Taher Pilehvar

message: Register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/spr1398" # the subpath of your site, e.g. /blog/
url: "https://iust-deep-learning.github.io/" # the base hostname & protocol for your site
githubdir: "iust-deep-learning/iust-deep-learning.github.io"

# Author/user information
email: instructor-last-name@iust.ac.ir
twitter_username: tpilehvar 
github_username:  pilehvar
authorurl: "http://webpages.iust.ac.ir/pilehvar/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css', '_js']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
